### ISSUE TITLE
Change templates

### ISSUE THREAD

**Issue by Wulfheart** [phpfui/InstaDoc#1]
Hello,
I would like to add custom templates. Is this possible?

**Comment by phpfui** [comment]
Not as currently designed, but I think it would be a good addition.

I would have to think about how to allow extending the classes so they could be customized.  It might not be that hard to do.  Right now the logic for figuring out what to output is fairly closely tied to querying the information from the models.

What specifically would you want to change?

**Comment by Wulfheart** [comment]
I don’t know yet. I would like to integrate it into a project of mine. 

Maybe splitting up the components (Class, Method, Variable, Enum, …) and defining a render function for each which could be overloaded will do the work.

**Comment by phpfui** [comment]
The original idea was to just have a page that is completely self contained.  But yes, your idea is in the right direction.

Another thing that could be done is embedding the rendering of a class into another page.  That would allow you skip the menu system.  I think it might do that already, as there are separate sections for the Doc, Git and Source pages.

This project is a direct result of not being able to get decent usable docs out of Packagist libraries easily and having to deal with bad and static document generators that took a lot of configuration.  So I prioritized setup simplicity over layout configuration.

In the end, there are not that many ways to present PHP documentation, since you want it to look like PHP method declarations, as we all know how to read them.  It really comes down to how to filter everything.  One thing it currently does not do is show all access levels (public, protected, private) in one view, but I find that is too confusing, as it makes it easier to call the wrong method from the wrong access scope.

But think about what you want to do and we can figure out a way to improve the package.

**Comment by Wulfheart** [comment]
Sure. I will think about it.

Btw, I have the exact same sentiment. That's why I wanted to create something like https://pkg.go.dev for PHP. The general architecture is already working (fetching updates from packagist, etc.) but I am still looking for simple method to render the documentation. PHPDocs only is not an option as the native typesystem got more sophisticated and made PHPDocs at some points useless (or at least they don't add more value). 
What do you think about it?

**Comment by phpfui** [comment]
Interesting idea. I had not seen the https://pkg.go.dev site, as I don't use GoLang.  But yes, a good idea for PHP.

Are you going to use Foundation for the UI?  If not, InstaDoc may not be a good idea, as it is a Foundation specific package.  Too embedded to remove (by design, makes it so much easier to write valid HTML code).  Funny thing is the Go site is filled with invalid HTML!  Pretty typical for most sites that use template includes, which is based on 1950's technology.

Thinking you might want to break out each section, which might be fairly easy.  I would work on a hand coded example page, when see what parts you need to break out.

**Comment by Wulfheart** [comment]
Ah okay. Then I am just going to create my own package for the documentation. I won't use foundation. What is it btw?

**Comment by phpfui** [comment]
Like Bootstrap, but better.

https://get.foundation/index.html
